version: 2.1

orbs:
  # Hold off on 8.2.x+ until the fix for https://github.com/CircleCI-Public/aws-ecr-orb/issues/256
  # is in a tagged version.
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

executors:
  outlandish:
    machine:
      image: ubuntu-2004:edge
      
workflows:
  deploy-staging:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: outlandish
          context:
            - ecs-deploys
          filters:
            branches:
              only:
                - develop
          repo: 'staging-wpackagist'
          tag: 'staging,staging-${CIRCLE_SHA1}'
          extra-build-args: '--build-arg env=stg'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          family: 'ol-ecs-staging-wpackagist'
          cluster: 'ol-ecs-staging-shared'
          service-name: 'staging-wpackagist'

  deploy-production:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: outlandish
          context:
            - ecs-deploys
          filters:
            branches:
              only:
                - main
          repo: 'production-wpackagist'
          tag: 'production,production-${CIRCLE_SHA1}'
          extra-build-args: '--build-arg env=prod'
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
          requires:
            - aws-ecr/build-and-push-image
          family: 'ol-ecs-production-wpackagist'
          cluster: 'ol-ecs-production-shared'
          service-name: 'production-wpackagist'
